// <auto-generated />
using System;
using EcommercePortfolio.Deliveries.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcommercePortfolio.Deliveries.Infra.Migrations
{
    [DbContext(typeof(DeliveryPostgresDbContext))]
    partial class DeliveryPostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcommercePortfolio.Deliveries.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateMade")
                        .HasColumnType("timestamp")
                        .HasColumnName("date_made");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("delivery_status");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("expected_date");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("Id");

                    b.ToTable("delivery", (string)null);
                });

            modelBuilder.Entity("EcommercePortfolio.Deliveries.Domain.Entities.Delivery", b =>
                {
                    b.OwnsOne("EcommercePortfolio.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("city");

                            b1.Property<int>("NumberAddres")
                                .HasColumnType("int")
                                .HasColumnName("number_addres");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("state");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("street_address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("varchar(20)")
                                .HasColumnName("zip_code");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
