services:
  ecommerceportfolio.orders.api:
    image: ${DOCKER_REGISTRY-}ecommerceportfolioordersapi
    container_name: ecommerce-portfolio-orders-api
    build:
      context: .
      dockerfile: services/Orders/EcommercePortfolio.Orders.API/Dockerfile
    ports:
      - "5010:5010"
      - "5011:5011"
    networks:
      - ecommerce_network
    depends_on:
      - postgresdb
      - redisdb
      - rabbitmq

  ecommerceportfolio.deliveries.api:
    image: ${DOCKER_REGISTRY-}ecommerceportfoliodeliveriesapi
    container_name: ecommerce-portfolio-deliveries-api
    build:
      context: .
      dockerfile: services/Deliveries/EcommercePortfolio.Deliveries.API/Dockerfile
    ports:
      - "5020:5020"
      - "5021:5021"
    networks:
      - ecommerce_network
    depends_on:
      - postgresdb
      - redisdb
      - rabbitmq

  ecommerceportfolio.carts.api:
    image: ${DOCKER_REGISTRY-}ecommerceportfoliocartsapi
    container_name: ecommerce-portfolio-carts-api
    build:
      context: .
      dockerfile: services/Carts/EcommercePortfolio.Carts.API/Dockerfile
    ports:
      - "5030:5030"
      - "5031:5031"
    networks:
      - ecommerce_network
    depends_on:
      - mongodb
      - redisdb
      - rabbitmq
  
  postgresdb:
    image: postgres:latest
    container_name: ecommerce-portfolio-postgres-db
    restart: always
    environment:
      POSTGRES_DB: EcommercePortfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  mongodb:
    image: mongo:latest
    container_name: ecommerce-portfolio-mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - mongo_data:/var/lib/mongo/data
    networks: 
      - ecommerce_network

  redisdb:
    image: redis:latest
    container_name: ecommerce-portfolio-redis-db
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - ecommerce_network

  rabbitmq:
    image: rabbitmq:4.0.8-management-alpine
    container_name: ecommerce-portfolio-rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks: 
      - ecommerce_network

volumes:  
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:

networks:
  ecommerce_network:
    