services:
  ecommerceportfolio.carts.api:
    image: ${DOCKER_REGISTRY-}ecommerceportfoliocartsapi
    build:
      context: .
      dockerfile: services/Carts/EcommercePortfolio.Carts.API/Dockerfile
    container_name: ecommerceportfolio-carts-api
    ports:
      - "5050:5050"
    networks:
      - ecommerce_network
    depends_on:
      - ecommerceportfolio-mongo-db
      - ecommerceportfolio-redis-db
      - ecommerceportfolio-rabbit-mq
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongo:mongo_password@ecommerceportfolio-mongo-db:27017
      - ConnectionStrings__RedisCache=redis://ecommerceportfolio-redis-db:6379
      - ConnectionStrings__RabbitMq=amqp://guest:guest@ecommerceportfolio-rabbit-mq:5672/
      - ApiSettings__FakeStoreApiUrl=https://fakestoreapi.com

  ecommerceportfolio.orders.api:
    image: ${DOCKER_REGISTRY-}ecommerceportfolioordersapi
    build:
      context: .
      dockerfile: services/Orders/EcommercePortfolio.Orders.API/Dockerfile
    container_name: ecommerceportfolio-orders-api
    ports:
      - "5150:5150"
    networks:
      - ecommerce_network
    depends_on:
      - ecommerceportfolio-postgres-db
      - ecommerceportfolio-redis-db
      - ecommerceportfolio-rabbit-mq
    environment:
      - ConnectionStrings__PostgresDb=Host=ecommerceportfolio-postgres-db;Port=5432;Database=EcommercePortfolioOrder;Username=postgres;Password=postgres
      - ConnectionStrings__RedisCache=redis://ecommerceportfolio-redis-db:6379
      - ConnectionStrings__RabbitMq=amqp://guest:guest@ecommerceportfolio-rabbit-mq:5672/
      - ApiSettings__CartApiUrl=http://ecommerceportfolio-carts-api:5050
      - ApiSettings__PaymentApiUrl=https://fakestoreapi.com

  ecommerceportfolio.deliveries.api:
    image: ${DOCKER_REGISTRY-}ecommerceportfoliodeliveriesapi
    build:
      context: .
      dockerfile: services/Deliveries/EcommercePortfolio.Deliveries.API/Dockerfile
    container_name: ecommerceportfolio-deliveries-api
    ports:
      - "5250:5250"
    networks:
      - ecommerce_network
    depends_on:
      - ecommerceportfolio-postgres-db
      - ecommerceportfolio-redis-db
      - ecommerceportfolio-rabbit-mq
    environment:
      - ConnectionStrings__PostgresDb=Host=ecommerceportfolio-postgres-db;Port=5432;Database=EcommercePortfolioDelivery;Username=postgres;Password=postgres
      - ConnectionStrings__RedisCache=redis://ecommerceportfolio-redis-db:6379
      - ConnectionStrings__RabbitMq=amqp://guest:guest@ecommerceportfolio-rabbit-mq:5672/
      - ApiSettings__OrderApiUrl=http://ecommerceportfolio-orders-api:5150

  ecommerceportfolio-postgres-db:
    image: postgres:17.5
    container_name: ecommerceportfolio-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  ecommerceportfolio-mongo-db:
    image: mongo:7.0.5
    container_name: ecommerceportfolio-mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce_network

  ecommerceportfolio-redis-db:
    image: redis:8.0.0
    container_name: ecommerceportfolio-redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce_network

  ecommerceportfolio-rabbit-mq:
    image: rabbitmq:4.0.9-management
    container_name: ecommerceportfolio-rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecommerce_network

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:

networks:
  ecommerce_network:

